apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "fleetmind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
