from __future__ import annotations

EVENT_RULES_VERSION = "fm-diagnostic-events-6.8.1-v1"

# Mirrors the predeclared Phase 6.7 transition semantics. These values are
# operational review thresholds, not calibrated failure-risk thresholds.
EVENT_RECENT_POINTS = 5
EVENT_INCIDENT_CONFIDENCE = 0.70
EVENT_ESCALATION_PER_1K_MILES = 0.01
EVENT_STABLE_FRACTION = 0.80
EVENT_VOLATILE_FRACTION = 0.60
EVENT_CONFIRMATION_WINDOWS = 2
EVENT_COOLDOWN_ANCHORS = 4

HYPOTHESIS_EMERGED = "HYPOTHESIS_EMERGED"
HYPOTHESIS_CHANGED = "HYPOTHESIS_CHANGED"
CONFIDENCE_ESCALATED = "CONFIDENCE_ESCALATED"
CONFIDENCE_DEESCALATED = "CONFIDENCE_DEESCALATED"
HYPOTHESIS_STABILIZED = "HYPOTHESIS_STABILIZED"
HYPOTHESIS_DESTABILIZED = "HYPOTHESIS_DESTABILIZED"

DIAGNOSTIC_EVENT_TYPES = (
    HYPOTHESIS_EMERGED,
    HYPOTHESIS_CHANGED,
    CONFIDENCE_ESCALATED,
    CONFIDENCE_DEESCALATED,
    HYPOTHESIS_STABILIZED,
    HYPOTHESIS_DESTABILIZED,
)
