from __future__ import annotations

from .diagnostic_event_rules import EVENT_RULES_VERSION

EPISODE_RULES_VERSION = "fm-diagnostic-episodes-6.9.1-v1"
EPISODE_SOURCE_EVENT_RULES_VERSION = EVENT_RULES_VERSION

# Episode-layer continuity only; model/event thresholds remain unchanged.
EPISODE_CONTINUITY_MAX_HEALTHY_GAP_MILES = 1000.0
EPISODE_CONTINUITY_MAX_INTERVENING_HEALTHY_EVENTS = 1

EPISODE_EMERGING = "EMERGING"
EPISODE_EVOLVING = "EVOLVING"
EPISODE_STABILIZED = "STABILIZED"
EPISODE_DESTABILIZED = "DESTABILIZED"
EPISODE_RESOLVED = "RESOLVED"
EPISODE_SUPERSEDED = "SUPERSEDED"

DIAGNOSTIC_EPISODE_STATES = (
    EPISODE_EMERGING,
    EPISODE_EVOLVING,
    EPISODE_STABILIZED,
    EPISODE_DESTABILIZED,
    EPISODE_RESOLVED,
    EPISODE_SUPERSEDED,
)

EPISODE_START_EMERGED = "EMERGED"
EPISODE_START_CLASS_CHANGED = "CLASS_CHANGED"
EPISODE_START_OBSERVED_IN_PROGRESS = "OBSERVED_IN_PROGRESS"
